### ISSUE TITLE
Audio Response Empty

### ISSUE THREAD

**Issue by justJS** [bespoken/virtual-device-sdk#51]
Whenever I use the node.js SDK, the audio response is empty.

**Comment by jperata** [comment]
Hi @justdotJS , a couple of checks, 
are you setting the token when using the SDK?
Second, if you're using the token, in your alexa app you should see in settings something like this
<img width="405" alt="screen shot 2017-12-12 at 10 15 38 am" src="https://user-images.githubusercontent.com/8781604/33891946-769fa4f2-df25-11e7-86c7-84e279ae8009.png">
if you have remove that ones from your account, you need to create a new token, since those are the devices against which the calls are generated.

**Comment by jkelvie** [comment]
Hi @justJS - any more information on this? If we don't hear back, we will close the issue.
